// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaCdJpnfQVqNc1bQq7ODnuGsCoQdGBQqQ',
    appId: '1:620007171981:web:e52f03527c77de6ae7ffc4',
    messagingSenderId: '620007171981',
    projectId: 'appenglishquiz',
    authDomain: 'appenglishquiz.firebaseapp.com',
    storageBucket: 'appenglishquiz.appspot.com',
    measurementId: 'G-Y28ZK45RLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7-IxHssYuKBJI8Duo4j4kWaxMtlhW1DU',
    appId: '1:620007171981:android:9005c3a027e9b216e7ffc4',
    messagingSenderId: '620007171981',
    projectId: 'appenglishquiz',
    storageBucket: 'appenglishquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_Cdi10VNen2bZ2UZJPaUyEUv0d6y_KY',
    appId: '1:620007171981:ios:03f1335703b295bae7ffc4',
    messagingSenderId: '620007171981',
    projectId: 'appenglishquiz',
    storageBucket: 'appenglishquiz.appspot.com',
    androidClientId: '620007171981-e0fj748014obktt89rl6te7i355nch23.apps.googleusercontent.com',
    iosClientId: '620007171981-oft6i2krurq1onjmr0ofumg1if7vmfri.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishquiz',
  );

}